dataset_path: '../../data/corentin/data/TerraMesh/val'
#dataset_path: '../../scratch/izar/suply/dataset/data/data/TerraMesh/' # Path to dataset
sensors_specs_path: 'pds_ECEO/spectrum/pretraining_sensors.yaml' # Path to sensors specs file
spectrum_specs_path: 'pds_ECEO/spectrum/electromagnetic_spectrum.yaml' # Path to spectrum specs file

experiments_dir: 'experiments/' # Outputs will be written to {experiments_dir}/{experiment.name}/

experiment:
  name: mlp_full_mask # Initialize with the name of the run
  seed: 42
  gpu: 0 # Set to None to use default GPU selection, or specify a GPU index (e.g., 0, 1, etc.)
  wandb_entity: corentin-suply-epfl
  wandb_project: TerraMesh
  wandb_mode: online # "online", "offline", or "disabled"

training:
  epochs: 10
  max_steps: 89600 # 71 680 images for training, # of images / batch_size = 8 960 * 10 epochs = 89600 steps
  batch_size: 2
  fp16: True
  bf16: False
  num_workers: 4
  gradient_accumulation_steps: 4
  lr: 0.0002
  lr_scheduler_type: cosine
  weight_decay: 0.01
  warmup_epochs: 2
  disable_eval: false

model:
  patch_size: 16
  model_dim: 512 
  feedforward_dim: 768
  encoder_pattern: hvhv
  num_encoder_heads: 4
  decoder_pattern: ff
  num_decoder_heads: 2
  num_decoder_hidden_layers: 0
  positional_embedding_type: rope
  dropout: 0.0
  group_layers: False
  norm_after_encoder_decoder: True

data:
  crop_size: 224
  masking_ratio: [0.6, 1.0]
  modalities:
  - "S2L2A"
  #- "S2L1C"
  - "S1RTC"
  sensors: [1, 2] # List of sensor indices to use (as defined in sensors_specs_path)
  shuffle: True
  return_metadata: False
  shardshuffle: 100
  deterministric: False
  time_dim: False
  partial: False
  probs: null

